@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package io.github.mrp_v2.morestickywires;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;